version: '3'
services:
  web:
    image: nginx
    expose: 
      - 80
    ports:
      - 80:80
    volumes:
      - ./static-html:/usr/share/nginx/html:ro
  django:
    build: .
    image: dungeon
    env_file: env
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres
    env_file: env
 
