version: '3'
services:
  web:
    build: web/
    image: web
    environment:
      - PORT=80
      - DATABASE_URL=postgres://dungeon_as_db_superuser@db:5432/dungeon_as_db
      - DEBUG=myapp:*
      - NODE_ENV=development
    volumes:
      - ./web/webapp:/usr/src/app:rw
    ports:
      - 80:80
      - 443:443
    command: npm run dev
  db:
    restart: unless-stopped
    build: db/
    image: db
    ports:
      - 5432:5432
    volumes:
      - ./db:/code
 
