version: '3'
services:
  api:
    restart: unless-stopped
    build: api/
    image: api
    ports:
      - 8000:5000
    volumes:
      - ./api:/usr/src/app
    environment:
      - DATABASE_URL=postgres://dungeon_as_db_superuser@db:5432/dungeon_as_db
      - PORT=5000
    command: npm run-script dev
  db:
    restart: unless-stopped
    build: db/
    image: db
    ports:
      - 5432:5432
    volumes:
      - ./db:/code
  web:
    restart: unless-stopped
    build: web/
    image: web
    volumes:
      - ./web/html:/usr/share/nginx/html:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
 
