version: '3'
services:
  rest:
    restart: unless-stopped
    build: rest/
    image: rest
    ports:
      - 8000:5000
    volumes:
      - ./rest:/code
    environment:
      - DATABASE_URL=postgres://dungeon_as_db_superuser@db:5432/dungeon_as_db
  db:
    restart: unless-stopped
    build: db/
    image: db
    ports:
      - 5432:5432
    volumes:
      - ./db:/code
  web:
    restart: unless-stopped
    build: web/
    image: web
    volumes:
      - ./web/html:/usr/share/nginx/html:ro
    ports:
      - 80:80
      - 443:443
 
