version: '3'
services:
  rest:
    restart: always
    build: rest/
    image: rest
    command: python app.py
    ports:
      - 8000:5000
    volumes:
      - ./rest:/code
  db:
    build: db/
    image: db
    ports:
      - 5432:5432
    volumes:
      - ./db:/code
  web:
    build: web/
    image: web
    volumes:
      - ./web/html:/usr/share/nginx/html:ro
    ports:
      - 80:80
      - 443:443
 
