version: '2'
services:
  web:
    build: .
    image: dungeon
    ports:
      - 80:8000
    links:
      - postgres:postgres
    env_file: env
    volumes:
      - .:/code

  postgres:
    image: postgres:latest
    env_file: env
    expose: 
      - 5432

