version: '3'
services:
  rest:
    build: .
    image: rest
    command: python app.py
    ports:
      - 8000:5000
    volumes:
      - .:/code/
  db:
    image: postgres
  web:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - 80:80
 
